wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685891242.817078
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.15.2
      8:
      - 3
      - 5
bl:
  desc: null
  value: 23
bias:
  desc: null
  value: 0.9
pop:
  desc: null
  value: 2
gen:
  desc: null
  value: 2
